### ISSUE TITLE
Problem with random numbers

### ISSUE THREAD

**Issue by jpolzfuss** [bluewaysw/pcgeos#100]
Hi!

Theoretically, this code should set randomX to a random number >=0 and < 100:

long double randomX;
randomX = 100;
FloatPushNumber(&randomX);
FloatRandomN();
FloatPopNumber(&randomX);

However, I'm always only getting numbers >=0 and < 1 like when calling "FloatRandom without N"?!

Kind regards,
Jörg

**Comment by jirkakunze** [comment]
Watcom only supports 64bit long doubles. So in your example randomX allocates 64bit on the stackframe. FloatPushNumber() is implemented in assembler and loads 80bit from stackframe and copies them to the FP stack. The value on the FP stack is now other than 100. FloatPopNumber() is also implemented in assembler and overwrites 80bit on the stackframe. So 2 bytes that do not belong to randomX are overwritten. We want to solve this problem with PR#84. The implementation is finished but not yet fully tested.

Jirka

**Comment by jirkakunze** [comment]
The branch is merged into the master. Please check it.

**Comment by jpolzfuss** [comment]
Fixed! :-)
