### ISSUE TITLE
Binaries?

### ISSUE THREAD

**Issue by javiergutierrezchamorro** [bluewaysw/pcgeos#11]
Are you going to release binaries/installer too?

**Comment by bluewaysw** [comment]
We plan to offer access to binary versions and other services for registered users here:

https://blog.bluewaysw.de (in bootstrap phase as of today)

Basic registration is free and assignes a personal serial number to every user that can be used in context with the distributed packages.

By default we prepare host system independent zip packages (of ensemble, sdk, etc) and hope to add installer versions some day based on community contributions and support.

There is a downloadable version of Breadbox Ensemble 4.13 in english there at the moment. So register today and get a free licence for GEOS.

**Comment by javiergutierrezchamorro** [comment]
Thanks. BTW, at some point Frank S. Fischer provided me a set of addons, you can get them here if interested:
http://www.javiergutierrezchamorro.com/wp-content/uploads/2013/08/breadbox_ensemble_addons.zip

It included a packet driver and a driver for TaskMax/TaskMgr.

**Comment by KBEELER2908** [comment]
I registered but haven't received a serial number for Breadbox Ensemble 4.13

**Comment by bluewaysw** [comment]
Your registration has been processed now, sorry for the delay.

Best,
Falk
