### ISSUE TITLE
swat core dumps if TERM is missing from TERMCAP

### ISSUE THREAD

**Issue by sduensin** [bluewaysw/pcgeos#114]
I attempted to run `swat` while using the `byobu` terminal utility.  `byobu` sets the `TERM` to be `screen-256color` which is not in the included `TERMCAP` loaded by `swat` resulting in:

```
TERMCAP=/home/scott/source/pcgeos/pcgeos/bin/termcapSegmentation fault (core dumped)
```

Changing my `TERM` to `xterm-256color` or `vt100` allows `swat` to run as intended.

Might be nicer to have an error message instead of program death.  :-)

**Comment by bluewaysw** [comment]
Added warning, swat continues in pure shell operation mode.
