### ISSUE TITLE
glue fail with ABNORMAL TERMINATION (for instance when building bbxbrow unsing Linux 64 bit sdk tools)

### ISSUE THREAD

**Issue by bluewaysw** [bluewaysw/pcgeos#120]
`--- AB/bbxbrowec.geo ---
rm -f AB/bbxbrowec.geo
glue  -Og /home/frehwagen/workspace/pcgeos/Appl/Breadbox/BbxBrow/bbxbrow.gp -P 1.0 -R 4.1.0.1 -E  -F./AB          `perl /home/frehwagen/workspace/pcgeos/Tools/scripts/perl/product_flags glue "AB" /home/frehwagen/workspace/pcgeos/Installed/Include /home/frehwagen/workspace/pcgeos/Installed/Include`  -m -L/home/frehwagen/workspace/pcgeos/Installed/Include -L/home/frehwagen/workspace/pcgeos/Installed/Include   -DCOMPILE_OPTION_FAVORITES -DGLOBAL_INTERNET_BUILD  -DCOMPILE_OPTION_AUTO_BROWSE       -T 1 -o AB/bbxbrowec.geo AB/ASMTOOLS.eobj AB/browser.eobj AB/sebrowse.eobj AB/FRFETCH.eobj AB/URLFRAME.eobj AB/URLTEXT2.eobj AB/URLTEXT.eobj AB/EXPIRE.eobj AB/INIT.eobj AB/URLFETCH.eobj AB/URLDOCCT.eobj AB/NAVIGATE.eobj AB/FAVORCLS.eobj AB/FAVORITE.eobj AB/BOOKMARK.eobj AB/NAVCACHE.eobj AB/BOOKCLAS.eobj AB/LOCALPAG.eobj AB/URLDOC.eobj AB/scrapbk.eobj AB/StatText.eobj AB/UIRare.eobj AB/GLBANIM.eobj AB/AWATCHER.eobj AB/HTMLVIEW.eobj AB/ImportG.eobj AB/UIAction.eobj AB/LoadURL.eobj AB/OpenClos.eobj AB/UIOften.eobj  
*** Empty segment: browser_TEXT
*** Empty segment: sebrowse_TEXT
*** Empty segment: BOOKMARK_TEXT
*** Empty segment: BOOKCLAS_TEXT
*** Empty segment: LOCALPAG_TEXT
Resource                          Size   # Relocs
-------------------------------------------------
CoreBlock                            0        0
dgroup                            6528      372
URLFETCH_TEXT                     3707       83
ASM_TEXT                           113        5
FRFETCH_TEXT                     16840      389
Warning: FRFETCH_TEXT is very large, that is a BAD thing.
URLFRAME_TEXT                    12599      310
Warning: URLFRAME_TEXT is very large, that is a BAD thing.
URLTEXT2_TEXT                     3056       66
URLTEXT_TEXT                     15027      335
Warning: URLTEXT_TEXT is very large, that is a BAD thing.
EXPIRE_TEXT                         26        0
INIT_TEXT                         3249      129
URLDOCCT_TEXT                      542       14
NAVIGATE_TEXT                     8581      203
FAVORCLS_TEXT                     6327      248
FAVORITE_TEXT                    11878      229
Warning: FAVORITE_TEXT is very large, that is a BAD thing.
NAVCACHE_TEXT                    11822      287
Warning: NAVCACHE_TEXT is very large, that is a BAD thing.
URLDOC_TEXT                       8149      242
scrapbk_TEXT                      3370      123
StatText_TEXT                     3393       77
UIRare_TEXT                       4128      170
GLBANIM_TEXT                      1046       21
AWATCHER_TEXT                      595       12
HTMLVIEW_TEXT                     2174       87
ImportG_TEXT                      3274       83
UIAction_TEXT                     4302      149
LoadURL_TEXT                      8825      282
OpenClos_TEXT                     3114      134
UIOften_TEXT                      2374       62
URLFetchEngineResource              48        1
HTMLResource                      2692        1
FavoritesStrings                   180        1
DocGroupResource                   132        1
UIResource                         144        1
ViewGroupTemplateResource           76        1
ViewTemplateResource               144        1
FrameResource                      228        1
FrameTemplateResource              120        1
TextResource                       432        1
GlobeResource1                    3100        1
GlobeResource2                    3100        1
GlobeResource3                    3100        1
GlobeResource4                    3100        1
GlobeResource5                    3100        1
GlobeResource6                    3100        1
GlobeResource7                    3100        1
GlobeResource8                    3100        1
GlobeResource9                    3100        1
GlobeResource10                   3100        1
GlobeResource11                   3100        1
GlobeResource12                   3100        1
GlobeResource13                   3100        1
GlobeResource14                   3100        1
GlobeResource15                   3100        1
AppResource                       1928        1
FileResource                       416        1
EditResource                       316        1
ViewResource                       928        1
OptionsResource                    672        1
NavigateResource                  1316        1
FavoriteManagerResource             44        1
FavoriteUIResource                 716        1
FavoriteUIOrganizeResource        1560        1
FavoriteUIListDialogResource       232        1
FavoriteCreateResource             448        1
FavoriteCreateGroupResource        728        1
LocalUIResource                     36        1
HTMLMenuResource                   352        1
WindowResource                      36        1
Interface                         5660        1
StatusResource                    5760        1
ToolbarResource                    308        1
DownloadDialogResource             828        1
CacheCleanupDialogResource         212        1
SearchResource                      36        1
SimpleToolbarResource             1776        1
HelpUIResource                     140        1
HelpFrameResource                  120        1
TopIcons1Resource                 3428        1
TopIcons2Resource                 2744        1
TopIcons3Resource                 2684        1
TopIcons4Resource                 4296        1
IconBarResource                     36        1
BboxLogoResource                    88        1
ExpireDialogResource                68        1
PCRootResource                      68        1
PCResource                        6632        1
ToolMonikerResource               2104        1
BREADBOXMONIKERRESOURCE            564        1
BREADBOXMONIKERRESOURCE2          2732        1
ImportThreadEngineResource          44        1
DownloadProgressDialogResource     640        1

Total size: 246431 bytes	    Fixed size: 10235 bytes
Warning: Fixed size should be reduced by moving things into movable resources
Uninitialized data/stack: 9994 bytes

Assertion Failed: VM_IN_USE(block), function VMLock, file /home/frehwagen/workspace/pcgeos/Tools/utils/vmLock.c, line 68.
ABNORMAL TERMINATION
*** Error code 1
pmake: 1 error
`

**Comment by HubertHuckevoll** [comment]
Can confirm.
![Screenshot 2022-11-13 20 20 31 - Display 2](https://user-images.githubusercontent.com/8293309/201541408-898ad50e-cef5-495c-96cc-4d6970fad3a5.png)

**Comment by mgroeber9110** [comment]
Another assertion that I have seen in the same situation (building `bbxbrow `spuriously fails in linking stage) is the following:
```
Assertion Failed: sd != NULL, function Pass2MS_ProcessObject, file C:\Geos\pcgeos\Tools\glue\pass2ms.c, line 1157.
ABNORMAL TERMINATION
```
If this is related, it may help us to narrow down the part of the code that goes wrong (and perhaps needs more instrumentation to catch the issue reproducibly).

**Comment by mgroeber9110** [comment]
Also seen with `webbox`
