### ISSUE TITLE
Reimplement compress library

### ISSUE THREAD

**Issue by bluewaysw** [bluewaysw/pcgeos#128]
Compress library is used for serveral application of PC/GEOS, centrally the help file system, but also word matcher and bindary uses compression.

Used algorithms are not included here anymore because there are licensed from PKWARE using an old version of implode. Source code is not available and we need to create an reimplementation of the algorithms. There are some open source reimplementations of implode but seems to be not 100% compatible but this might be a good starting point.

**Comment by danielnez1** [comment]
Hello,

Firstly, I apologise if this means more work for you, feel free to ignore :)

I was going to open a issue about this but I will add it here as a comment. Could you  possibly compile a list of proprietary components that have been removed from the FreeGEOS source tree? From my observations I thought it was at least the fonts and some of the file conversion source files removed, though to my surprise it looks like spelling dictionaries and thesaurus data files have been retained. 

Cheers,

Dan

**Comment by bluewaysw** [comment]
Thank you for the remarks and question, we are on it! We likely will publish infos on status and road map soon, once they are consolidated and ready for prime time.
