### ISSUE TITLE
Noisy Watcom warnings W303

### ISSUE THREAD

**Issue by bolle732** [bluewaysw/pcgeos#130]
Compiling Geodes with `pmake` produces a lot of Watcom warnings W303.

They look like:
```
test.goc(<Line#>): Warning! W303: Parameter 'oself' has been defined, but not referenced
test.goc(<Line#>): Warning! W303: Parameter 'message' has been defined, but not `referenced
```

This warnings can be suppressed with the following pragma in the code file (in this example file `test.goc`)
`#pragma disable_message(303)`

As suppressing warnings is not always a good idea, the GOC compiler / toolchain should make sure no such warnings would be generated if not needed.

**Comment by bluewaysw** [comment]
It seems hard to implement some generic touch statement here as goc does for other compilers. WATCOM seems especially strict in separating variable declaration and statements in a C function body.

Checking WATCOM specs it states W303 is of by default as seen here:
https://users.pja.edu.pl/~jms/qnx/help/watcom/compiler-tools/cmsgs.html
This seems not true for open-watcom 2.0, but might point us to the only valid solution here to force it of for goc files.

**Comment by bluewaysw** [comment]
Fixed by latest master. pragma is used to disable the warning message, once a first method implementation is parsed by goc executing a .goc file. Warning will not be enabled again for the rest of the .goc file.
