### ISSUE TITLE
Localization process setup

### ISSUE THREAD

**Issue by bluewaysw** [bluewaysw/pcgeos#153]
We need to setup an localization process because upcoming 2022 ensemble release is planned to become available in english and german initially.

**Comment by JMGeithain** [comment]
OK I will made the german language files with ResEdit.

**Comment by frehwagen** [comment]
Yes, ResEdit is the right tool use! I started to setup the process to use those files to generate a compelte german ensemble automatically, half way through.

**Comment by bluewaysw** [comment]
When looking at the available tools that are in the source we have that deal with product localization there seem to be 2 approaches:

1. There are dedicated products setup that produce different file set, locallization likly happed manuelly using ResEdit
2. There is an hidden option to select target languages in build.pl, that uses PC/GEOS with ResEdit as server to translate files to target languages when building the target file tree. There seems no source code available for the specific version of ResEdit that is required here

Based on this we will implement an new 3rd approach targeting the following goals:

- have one product definition for multiple target languages, define language specific target files conditionally when specifying the file tree
- use ResEdit batch mode (triggered automatically) to translate the entire product in one run
- control the translation and the target language by setting an environment variable, so that the currently used interactive build interface of build.pl doesn't change

**Comment by bluewaysw** [comment]
We will use the environment variable TARGET_LANG to specifiy the required target language if different from english. This option set triggers the additional translation processing step of the target product file set.

**Comment by bluewaysw** [comment]
Translation files will live in a language specific folder of the product file space in a new Trans subfolder. This folder is given to RedEdit for batch processing.

German translation files for instance will live here:
`pcgeos/Tools/build/product/bbxensem/Trans/german`

**Comment by bluewaysw** [comment]
The build process uses a specific _tool target to execute the translation task. This ensemble setup autoruns ResEdit at startup. Having folders mounted for source and target geos file tree together with a folder containing all translation files. 

The GEOS.INI file contains the relevant information (for instance):

```
[resedit]
sourceDir = C:\TSRC\ENSEMBLE
destinationDir = C:\TDEST\ENSEMBLE

batchLogFile = C:\TRANSLOG.TXT
autorunBatchDir = c:\TRANS
```

ResEdit has been modified to support  2 new ini keys:

_autorunBatchDir_ points to the location of the translation file to be applied. If this is configured ResEdit automatically runs the batch process on startup and when done forces GEOS to exit (to give control back to the CI process).

_batchLogFile_ points to an optional log file to be created from the batch process output. This in result is incooperated into the build process log file, also available here in github as part of each build linked log file.

**Comment by bluewaysw** [comment]
Localization tool chain is now active and produces german versions of current builds automatically as part of the build artifact as you may find them here:
