### ISSUE TITLE
GeoFile

### ISSUE THREAD

**Issue by JMGeithain** [bluewaysw/pcgeos#156]
GeoFile is starting with KR-07

**Comment by bluewaysw** [comment]
Basic issue is that WATCOM produces a slighly different class layout, espeically for the CMethod paramter part of the class tables that is not padded to work boundary. This becomes an issue if the class declares an _reloc method. A pointer to the method is stored after the CMethod parameter table and is misalinged cuurendly.

**Comment by bluewaysw** [comment]
Fixed key issues to make GeoFile work on the lateset master. There is still more testing needed and dedicated bugs should be addressed using new issues here. There is one issue that going to be covered by another issue as well:
Parts of the GeoFile implementation puts const structures into code segment to save dgroup space. The -zc option of WATCOM leads to some glue issues that needs investigation and fixing.
