### ISSUE TITLE
Link issue then using -zc watcom option to allocate const structures and literals in code segments

### ISSUE THREAD

**Issue by bluewaysw** [bluewaysw/pcgeos#165]
The approach above is used in original GeoFile mModes.goc file. If active glue isn't able to link the Geode anymore. This needs to be fixed, to enable GeoFile (and others) to save dgroup space.

**Comment by bluewaysw** [comment]
Thx, @rabe-soft for triggering reevaluation! Did you check with GeoFile as well? What version of WATCOM are you using?

**Comment by rabe-soft** [comment]
@bluewaysw I have just tried it. Geofile does not compile with -zc flag set:
glue  -Og D:/G6/PCGEOS/Appl/GeoFile/geofile.gp -P 11.0 -R 4.1.0.1 -E -z  -F./          -DPRODUCT_ -DHARDWARE_TYPE_PC  -m -LD:/G6/pcgeos/Installed/Include -LD:/G6/PCGEOS/Installed/Include   -r -T 1 -o geofileec.geo DocAsm.eobj docGroup.eobj document.eobj strings.eobj mAppl.eobj mFldOrdr.eobj mFldOrgz.eobj mLayouts.eobj mModes.eobj mProcess.eobj mSorting.eobj mSubsets.eobj uiLayout.eobj uiMain.eobj uiMarked.eobj uiModify.eobj uiTmplat.eobj
Error mAppl.eobj: non-data FIXUPP record may only contain THREAD definitions
Error mAppl.eobj: non-data FIXUPP record may only contain THREAD definitions
Error mModes.eobj: non-data FIXUPP record may only contain THREAD definitions
Error mModes.eobj: non-data FIXUPP record may only contain THREAD definitions
Error mModes.eobj: non-data FIXUPP record may only contain THREAD definitions
*** error code 5

Im using
Open Watcom C x86 16-bit Optimizing Compiler
Version 2.0 beta Dec  1 2020 00:27:51 (32-bit)

**Comment by bolle732** [comment]
I tried it too on Ubuntu `20.04.6 LTS`  with my little GeoLadder and `Version 2.0 beta Dec  1 2020 00:27:45 (64-bit)`. I get teh FIXUPP messages too when using `-zc`.

```
glue   -Og geoladder.gp -P 0.4 -R 0.4.2.17 -z -F./          `perl /home/bolle/pcgeos/Tools/scripts/perl/product_flags glue "" /home/bolle/pcgeos//Include /home/bolle/pcgeos/Installed/Include`  -m -L/home/bolle/pcgeos//Include -L/home/bolle/pcgeos/Installed/Include   -N �2010\20by\20YoYu-Productions -T 4 -o geoladder.geo process.obj ladgame.obj visobj.obj appui.obj  
Error process.obj: non-data FIXUPP record may only contain THREAD definitions
*** Error code 1
pmake: 1 error
```

**Comment by bolle732** [comment]
@rabe-soft Very good finding! I had several `static const` and replaced them with only `static`. Now, the code compiles with `-zc` in `local.mk`.

The resulting size of the Geode with and without `-zc` is the same. Both are `21'758` bytes. The version with the old SDK using Borlands `bcc` is `17'876` bytes. Maybe there are still other optimizations possible.

**Comment by rabe-soft** [comment]
A small correction: The problem also occurs if the array contains only optr (e.g. static const optr testList[] = ...). Aditionally the code lines
`static const GenAppUsabilityTuple * const vfar usabilityTable [] =
	DesignModeList,
	GraphicsLayerList,
...`
need to be changed by removing the 2nd const keyword to
`static const GenAppUsabilityTuple * vfar usabilityTable [] =
...`

After all changes have been made, GeoFile compiles and runs with the -zc flag set. The dgroup size has been reduced from 1344 to 1200 bytes. @bolle732 IMHO I think, static variables must reside in the dgroup, they cannot be moved to any code resource.

**Comment by bluewaysw** [comment]
Done, merged to master.
