### ISSUE TITLE
The "cvtpcx"-tool is missing from the SDK tools.

### ISSUE THREAD

**Issue by HubertHuckevoll** [bluewaysw/pcgeos#198]
The tool is needed to convert pcx files into GEOS Graphics Strings, which can then be added as monikers and such. Many apps in the source code have script files that call "cvtpcx", these are currently non-functional.

**Comment by bluewaysw** [comment]
Done, added cvtpcx to the tools beeing built, merged to master.

**Comment by HubertHuckevoll** [comment]
Wonderful, thank you very much!
