### ISSUE TITLE
CarMilage Formula

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#202]
https://github.com/bluewaysw/pcgeos/blob/a8ad8befb9caffb42b659002f6804c41e926192f/Appl/BigCalc/bigcalcData.ui#L713
 chunk	CarMilageFormula	= "$2/($1-$0)*100"

**Comment by bluewaysw** [comment]
Could you document here what $0 $1 $2 is? @nschulux

**Comment by nschulux** [comment]
That are the field in the Worksheet.
