### ISSUE TITLE
pscript.geo is broken

### ISSUE THREAD

**Issue by rabe-soft** [bluewaysw/pcgeos#215]
Installing any PostScript printers fails.
1. Open Preferences, select Printer
2. Click on New ...
3. Select any of the PostScript printers and click on OK. The port does not matter.
4. Click on Test. You will see the error message shown in the screenshot.

The problem does not occur with non-PostScript printers. The reason is the pscript.geo. 
If you replace it with another version (I used the one updated by Jens-Michael Groß in 2004), the printers can be installed after the target has been restarted.
In the NC version of the target, they work fine now, but in the EC version only blank pages are printed.
![Printer](https://user-images.githubusercontent.com/45405983/209836509-a16196c8-09b6-4e4c-b6c2-d4e7f4a189b2.JPG)

**Comment by nschulux** [comment]
ps2pdf.geo is missing in Freegeos !
![PS TO PDF](https://github.com/bluewaysw/pcgeos/assets/118665816/5d9d526d-254c-4e32-a193-3e7882e7ea41)

**Comment by nschulux** [comment]
https://github.com/bluewaysw/pcgeos/blob/master/Library/Breadbox/ps2pdf/ps2pdf.goc
Should be added to Freegeos !

**Comment by rabe-soft** [comment]
Alternative solution: The dependency of pscript.geo on ps2pdf.geo is removed. Its core functionality (shutting down GEOS and calling GhostScript on DOS level) is currently not used anymore, isn't it?
In the short term, Nico's suggestion is probably easier to implement.

**Comment by nschulux** [comment]
ADDED PS2PDF to FreeGeos !

**Comment by bluewaysw** [comment]
Fix merged to master.
