### ISSUE TITLE
Resource names and chunk names are not shown during localization

### ISSUE THREAD

**Issue by rabe-soft** [bluewaysw/pcgeos#217]
The Resource Editor does not display the true names of resources and chunks when localizing. Instead, it uses generic names like Resource12 and Chunk5.
This is a really BIG problem, because the resource editor matches the original chunks and the translated chunks by their order instead of their names. If you change the position of an object or add new objects the order is no longer correct and the translated chunks are incorrectly assigned or "recognized" as new or deleted. 

The problem seems to be already in glue or before. Using loc.exe from the old 16 bit SDK does not help.

**Comment by bluewaysw** [comment]
What is the actual issue here @rabe-soft , the nameing or the order?

**Comment by rabe-soft** [comment]
I think, the naming is the issue, but this seems to cause scrambling the order and the content of translated texts after updating.

This picture shows my original file to translate the Uni Installer from German to Englisch. You can see resource names and chunk names. With the old SDK, I can add and remove objects, change its order and after updating the translation file anything is OK.
![Original German To English](https://user-images.githubusercontent.com/45405983/210631737-45732cd6-0bc9-4431-b84f-d92f63b125b3.JPG)

The next two pictures show a newly created translation file from the German version of the Uni Installer. The app was compiled using the new SDK and also the translation file has been created with the localize app from the new SDK. There are generic names for chunks and resources. I have changed any translated chunk by inserting an asterix to tell the resource editor (localize.geo) that the chunk has been translated.
![New - German, untranslated](https://user-images.githubusercontent.com/45405983/210633780-1992fb8a-be99-4cda-afc5-294fe3fbc52f.JPG)
![New - German, untranslated Texts ](https://user-images.githubusercontent.com/45405983/210634260-201375c7-ba67-43cf-bb6f-72941d60fbcf.JPG)

Until this point, anything seems to be OK. But then I have inserted a new object with a visMoniker in the code. After updating the translation file, the translated chunks are no longer correctly assigned and partly also changed. As you can see, the chunk names has been changed too.
![New - updated](https://user-images.githubusercontent.com/45405983/210634961-ce7c935a-4aa9-4eb9-b502-f2c5c98fd020.JPG)

![New - updated - Texts](https://user-images.githubusercontent.com/45405983/210636056-f85bfb6e-fc55-4f9d-a82d-94d14c723d27.JPG)

I have also tried the localize app and loc.exe from the old SDK (as you can see in the pictures) but this does not solve the problem. There are still generic names for chunks and resources. Therefore I assume theat the problem is located in glue while creating the sym file.

**Comment by bluewaysw** [comment]
Fix implemented, tested and merged to master. Issue was triggered by uppercase and lowercase handling differences of resource names in the process.

**Comment by bluewaysw** [comment]
Addon remark: The good thing with the related issue is, that none the less the translation files can be successfully used even if the label is not properly given by the source vm file. Even better it seems the translation files may be update to correct labels by updating them to an corrected vm file.
