### ISSUE TITLE
Glue: disassembly of C functions fails after one or two pages of code

### ISSUE THREAD

**Issue by mgroeber9110** [bluewaysw/pcgeos#225]
When listing the disassembly of a large function in Swat with a command such as

    listi _TT_MulDiv

followed by pressing _Enter_ again for the next page of code, I am getting an error such as `Error:   ttcalc_TEXT::_TT_MulDiv: no such scope is defined`, with two random characters after the word "Error:" that change each time. It looks like there is a point in the function beyond which disassembly is no longer possible. This can be checked by entering an offset into the function, e.g.

    listi _TT_MulDiv+71

Perhaps this is a problem with how Glue converts some debug infos (producing invalid symbol records in the in SYM file)?

This was seen with the truetype.geo driver from [this commit](https://github.com/jirkakunze/pcgeos/commit/d51119e3eeee70755ff0e7b7b5f116a61e44f533).

**Comment by mgroeber9110** [comment]
This is caused by an empty string as a name for a "lexical block" scope in the debugging information. Because of this. the buffer for the result of `Sym_FullName` is allocated two bytes too big (for the `::` character that never gets inserted), and starts with 2 garbage bytes, because it is filled from back to front.

Ultimately, this is a result from the conversion of the debug information for C code in `glue`: it looks like a scope with an empty name should also be assigned a ``??block0`` pseudo name, just as if it did not have a name string at all.

I will fix this on the TTF branch.

**Comment by bluewaysw** [comment]
The fix has been merged to master so lets close this issue.
