### ISSUE TITLE
German translation for motif and isui are incomplete

### ISSUE THREAD

**Issue by bluewaysw** [bluewaysw/pcgeos#228]

**Comment by nschulux** [comment]
OLDocumentControlUI :RecoverFromQuickBackupTrigger_Moniker
Aus Backup wiederherstellen

**Comment by bluewaysw** [comment]
Updated translations files:

- Motif
- ISUI
- Calculator

with latest vm files (see #221). Incooperated some missing translation and fixes.

Translation build log now is clean:
Beginning batch process.
Handling 600 Access Point Database
Handling 600 Address Book (Adressbuch)
Handling 600 Artist (GeoDraw)
Handling 600 Background Module
Handling 600 Banker 3.0
Handling 600 Banner Maker (GeoBanner)
Handling 600 BBX Mail Library
Handling 600 Bitmap Library
Handling 600 Bitmap Metafile Converter
Handling 600 Book Reader Library
Handling 600 Book Reader
Handling 600 Breadbox File List Library
Handling 600 Breadbox FTP Library
Handling 600 Breadbox HTML4 Parse Library
Handling 600 Breadbox Internet Msg Librar
Handling 600 Breadbox Num to text Library
Handling 600 Breadbox Site List Database
Handling 600 Calculator (Rechner)
Handling 600 Calenar (Terminkalender)
Handling 600 Card Library
Handling 600 CD Player (CD-Player)
Handling 600 CD ROM IFS driver
Handling 600 Chart Library
Handling 600 Character Map (Zeichensatzta
Handling 600 Chat
Handling 600 Clock (Uhr)
Handling 600 Color Library
Handling 600 Columns II
Handling 600 Computer Module
Handling 600 Configurations Library
Handling 600 Configure UI Module
Handling 600 Crossword (Kreuzwort)
Handling 600 Date & Time Module
Handling 600 DialUp&Configure (Internet-E
Handling 600 Directory List Support
Handling 600 DirList
Handling 600 DOS Default Launcher
Handling 600 DR DOS IFS driver
Handling 600 Email
Handling 600 File Transfer
Handling 600 File Finder (Dateisuche)
Handling 600 Flat File Library database
Handling 600 Font Module
Handling 600 Game Library
Handling 600 Generic User Interface
Handling 600 GeoComm
Handling 600 GeoCalc (Spreadsheet)
Handling 600 GeoFile
Handling 600 GeoManager
Handling 600 GeoPoint
Handling 600 Geos Module
Handling 600 GEOS kernel
Handling 600 GeoWrite (Writer)
Handling 600 GeoZip Breadbox-Version
Handling 600 Graphical Setup
Handling 600 Graphic Object Library
Handling 600 Graphics Viewer Grafik-Viewe
Handling 600 HomeBase
Handling 600 Instant Messenger
Handling 600 International Module
Handling 600 ISDesk
Handling 600 ISUI_NEW
Handling 600 Keyboard Module
Handling 600 KidGuard Module
Handling 600 Lights Out
Handling 600 Lights Out Module
Handling 600 Light Out Launcher
Handling 600 Link Creation Tool
Handling 600 Macro Recorder (Macro-Record
Handling 600 Motif Specific UI_NEW
Handling 600 Mouse Module
Handling 600 MS DOS 4X FS Driver
Handling 600 NewsReader
Handling 600 PDF Viewer
Handling 600 Perf
Handling 600 Print Spool Library
Handling 600 Scrapbook (Sammelalbum)
Handling 600 Screen Dumper
Handling 600 Soliaire
Handling 600 Sound Module
Handling 600 SysTray Clock
Handling 600 Text Library
Handling 600 Text File Editor (Notoitbloc
Handling 600 Video Module
Handling 600 Voreinstellungen Preferences
Handling 600 WebMagick 3.0
Handling 600 Word Matcher
Batch process completed.

**Comment by nschulux** [comment]
Translated Bicclac Worksheet uncompleted.
I have copied  translation to biccalc from ensemble 4.1.3 patch based on Johannes.
Opened 2 Resedit and copied just the Translationtext.
In Isui and Motif I have changed Beenden to Beende why ist better understanding !
"Beenden Geowrite" is like "Exits Geowrite" !
Nico
[RESEDIT3.zip](https://github.com/bluewaysw/pcgeos/files/12578092/RESEDIT3.zip)
