### ISSUE TITLE
Geocalc teils in englisch!

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#247]
The Librarys math sheet parse and spell must be translated.
I will try to do it this week.

**Comment by nschulux** [comment]
![Geocalc2](https://github.com/bluewaysw/pcgeos/assets/118665816/8d0c7d48-b4a7-4094-bf75-015d8a6ecb95)
![Math](https://github.com/bluewaysw/pcgeos/assets/118665816/473fec1c-27ab-4712-b864-d98f41f4f17e)

**Comment by nschulux** [comment]
Pull request: Geocalc partially in english #249

**Comment by bluewaysw** [comment]
Fixed and merged to master.
