### ISSUE TITLE
Ensemble apps can't open the Breadbox GIF Import Library

### ISSUE THREAD

**Issue by HubertHuckevoll** [bluewaysw/pcgeos#281]
When trying to "import graphic" in the Icon Editor or GeoDraw and selecting a GIF file, the app fails. The built-in GEOS Graphics Viewer has no problem opening GIF's.
![Screenshot 2023-11-20 19 32 26](https://github.com/bluewaysw/pcgeos/assets/8293309/aafa12a2-d008-4595-a0eb-c5fe950b862e)
![Screenshot 2023-11-20 20 13 03](https://github.com/bluewaysw/pcgeos/assets/8293309/5b094997-6df4-4a87-8ed3-a91459d3e192)

**Comment by bluewaysw** [comment]
Fix merged to master.
