### ISSUE TITLE
world/utilitys/clock in digitalclock-View does not switch between 12h an 24h  (german Build only)

### ISSUE THREAD

**Issue by lockesoft66** [bluewaysw/pcgeos#291]
Dieser Fehler tritt nur in der Deutschen Version auf. :-)
Die Englische funktioniert problemlos.
In der Ansicht Digitaluhr und auch (nachträglich angetestet) bei sceleton wird immer der 24 h Modus genutzt. Umschalten auf 12 h ändert die Anzeige nicht.
Ab wann der Fehler konkret aufgetaucht ist vermag ich nicht  genau zu sagen. In einer der ersten Deutschen Versionen, die seit kurzem wieder verfügbar sind ist er jedenfalls schon drin.

This Issue is only in German Freegeos. :-)
English build works ok.
In the View DigitalClock  and Sceleton-view 24h Mode is always used. Switching  does not Chance anything..
i Can´t say at what Moment this bug happens. It is still in the first German Version from Last Month

**Comment by nschulux** [comment]
Auch in Voreinstellungen International da gibt es am und AM eins müsste PM sein.
Könnte damit zusammenhängen.

**Comment by lockesoft66** [comment]
hmmh. das scheint wohl wirklich so. Ok ich schliesse auch das Teil. Ich denke aber, das sollte etwas deutlicher gemacht werden. Im Voreinstellungen-Modul eine Beschriftung an der Option und in beiden Hilfedateien (Voreinstellungen International und Datum / Uhrzeit) ein Hinweis auf das mögliche Fehlen von Reaktionenund Optionen. Optionen, weil in Voreinstellungen Uhrzeit ändert sich die  Einstellmaske. Reaktion, weil Man kann es in der Uhr ja immer noch einstellen, ändert nur nix :-)
