### ISSUE TITLE
PDFViewer empty screen.

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#311]
PDFViewer opens PDF but no Text.
![pdf](https://github.com/bluewaysw/pcgeos/assets/118665816/25ca330c-f5fb-44fc-a3f1-35319ba1fc6e)

**Comment by bluewaysw** [comment]
What version had the pdf file you used @nschulux ? So far PDF Viewer only support PDF file versions up to 1.2.

**Comment by nschulux** [comment]
I tested now with Docs from FreeSdk wich is Version 1.1 all is OK.
Other PDF was from Rainer Basic manuals they are 1.3 from Mac.
