### ISSUE TITLE
Nimbus Sans TTF print fault

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#312]
FONT Nimbus Sans (URW)++,Copyright 2014 by (URW)++ Design & Development  
https://github.com/twardoch/urw-core35-fonts
I tried URW ++ Nimbus Sans and Nimbus Roman optimized with fontsquirrel.com.  254 Characters. (Tip from Jirka!)
Print to PS.

![Fehler](https://github.com/bluewaysw/pcgeos/assets/118665816/19150848-9cda-4f05-9f27-c0dcfb5f3bdd)
[NSANS.zip](https://github.com/bluewaysw/pcgeos/files/13625443/NSANS.zip)

**Comment by nschulux** [comment]
Nimbus SansL optimized with fontsquirrel.com. 254 Characters. (Tip from Jirka!)
Works. Print to PS.
![NimbusSansL](https://github.com/bluewaysw/pcgeos/assets/118665816/0eecf5b2-78eb-415d-8d6e-2d842c27e0f4)
Only problem "fett" should be Bold. Perhaps fault of gsview (GhostscriptView)?

**Comment by bluewaysw** [comment]
@nschulux please double check and confirm if it has been fixed, should be in master.

**Comment by nschulux** [comment]
No Bold in ps file in Gsview
No Font Nimbus Sans it's not working.
![NimbusSans-Print Fault](https://github.com/bluewaysw/pcgeos/assets/118665816/8245a000-2fc3-44d1-990b-ab4ce53329ac)
DRFONT.PS here to check.
[DRFONT.zip](https://github.com/bluewaysw/pcgeos/files/13795649/DRFONT.zip)

**Comment by nschulux** [comment]
![Neue Schriften2](https://github.com/bluewaysw/pcgeos/assets/118665816/0b0ea44f-7e56-4d37-a3c8-cc8b40c4ea84)
I am not sure but fonsquirrel create now font with other Size ! Updated ? 
Works now !
