### ISSUE TITLE
Automatic Backup in Preferences has Two SwitchOn Option in German Build

### ISSUE THREAD

**Issue by lockesoft66** [bluewaysw/pcgeos#319]
In the actual German Build (older builds too)
The App Preferences ---> Section---> Configure UI ---> Advanced ---> Document Safeguarding
Both Radiobutton are named with "on"

Im aktuellen Deutschen Build (auch ältere Versionen)
hat die App Voreinstellungen im Bereich UI einstellen ---> Sonstiges ---> Automatische Dokumentensicherung
beide Radiobutton mit "ein" (schalten) beschriftet
![Prereferences-e6de-vom08 12](https://github.com/bluewaysw/pcgeos/assets/99907210/b23f8941-f77f-4f76-a2db-90ad76486212)

**Comment by nschulux** [comment]
PR created.

**Comment by bluewaysw** [comment]
Merged to master, should be fixed in latest CI build.
