### ISSUE TITLE
Add Home Inventory and Gourmet application

### ISSUE THREAD

**Issue by bluewaysw** [bluewaysw/pcgeos#327]
We have the source code to add and want it to be part of FreeGEOS release builds for now, for testing.

**Comment by nschulux** [comment]
Good !

**Comment by bluewaysw** [comment]
Application has been added to repo and release. HelpFile sources and german help file is missing. German translation for the Geode as well.

**Comment by nschulux** [comment]
I have the gernan translation i will correct to the current version and upload it.
