### ISSUE TITLE
Standard SymbolPS Crash System.

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#331]
StandardSymbolPS.ttf PC/Geos stürtzt unwillkürlich ab.
[StandardSymbolsPS.zip](https://github.com/bluewaysw/pcgeos/files/13625430/StandardSymbolsPS.zip)

**Comment by jirkakunze** [comment]
Do program crashes really occur because of this font? 

My investigations have shown that this font is not registered in GEOS. The reason is that this font only contains a charmap with the PlatformID 3 (Microsoft) and the encoding 0 (Symbol). This encoding is not supported by the TTF driver because such fonts usually only contain characters with unicodes that cannot be mapped to the GEOS character set. Specifically, the problematic font contains Unicode characters from 0xf020 to 0xf0fe. In this one case, the code 0xf020 could be mapped to the GEOS character 0x20 and so on. This would probably only help for this one font and I would not like to deal with such special cases in a driver. 

However, I have seen symbol fonts that map the symbols to the 'normal' Unicodes/Ascii codes. Such fonts are certainly the better choice for us.

**Comment by nschulux** [comment]
I have szip the Original Font afther I have optimized this Font with
fontsquirrel.com , then Ihave had the Crashs.


Attached the Font !


From Nico


Am 09.12.2023 um 22:37 schrieb Jirka Kunze ***@***.***>:



Do program crashes really occur because of this font?

My investigations have shown that this font is not registered in GEOS. The
reason is that this font only contains a charmap with the PlatformID 3
(Microsoft) and the encoding 0 (Symbol). This encoding is not supported by the
TTF driver because such fonts usually only contain characters with unicodes
that cannot be mapped to the GEOS character set. Specifically, the problematic
font contains Unicode characters from 0xf020 to 0xf0fe. In this one case, the
code 0xf020 could be mapped to the GEOS character 0x20 and so on. This would
probably only help for this one font and I would not like to deal with such
special cases in a driver.

However, I have seen symbol fonts that map the symbols to the 'normal'
Unicodes/Ascii codes. Such fonts are certainly the better choice for us.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by nschulux** [comment]
I have copied the characters to the front of the Font !


Test If this can work !


Am 09.12.2023 um 22:37 schrieb Jirka Kunze ***@***.***>:



Do program crashes really occur because of this font?

My investigations have shown that this font is not registered in GEOS. The
reason is that this font only contains a charmap with the PlatformID 3
(Microsoft) and the encoding 0 (Symbol). This encoding is not supported by the
TTF driver because such fonts usually only contain characters with unicodes
that cannot be mapped to the GEOS character set. Specifically, the problematic
font contains Unicode characters from 0xf020 to 0xf0fe. In this one case, the
code 0xf020 could be mapped to the GEOS character 0x20 and so on. This would
probably only help for this one font and I would not like to deal with such
special cases in a driver.

However, I have seen symbol fonts that map the symbols to the 'normal'
Unicodes/Ascii codes. Such fonts are certainly the better choice for us.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by nschulux** [comment]
I have found other font.
Remapped for PC/Geos.

**Comment by nschulux** [comment]
I have found another font and remapped for PC/GEOS.


From Nico


Am 09.12.2023 um 22:37 schrieb Jirka Kunze ***@***.***>:



Do program crashes really occur because of this font?

My investigations have shown that this font is not registered in GEOS. The
reason is that this font only contains a charmap with the PlatformID 3
(Microsoft) and the encoding 0 (Symbol). This encoding is not supported by the
TTF driver because such fonts usually only contain characters with unicodes
that cannot be mapped to the GEOS character set. Specifically, the problematic
font contains Unicode characters from 0xf020 to 0xf0fe. In this one case, the
code 0xf020 could be mapped to the GEOS character 0x20 and so on. This would
probably only help for this one font and I would not like to deal with such
special cases in a driver.

However, I have seen symbol fonts that map the symbols to the 'normal'
Unicodes/Ascii codes. Such fonts are certainly the better choice for us.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>
