### ISSUE TITLE
Contacts double !

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#348]
CONTACTS.000 should be contacts.geo !
geodex.geo shoukd be removed is english version !
Geodex
![Geodex](https://github.com/bluewaysw/pcgeos/assets/118665816/40f9111a-8dd8-445b-8e94-edc7e0d5bcf0)

**Comment by bluewaysw** [comment]
The permanent name geodex should not change, so does the .geo name stick to geodex as well. This change is only about the long name. We need to figure out why the translation step generated CONTACTS.000 instead of overwriting the geodex.geo file.

**Comment by rabe-soft** [comment]
The problem that a CONTACTS.000 file is created for 'Kontakte' instead of overwriting geodex.geo (Contacts) is due to an (unknown) problem in the translation file. I overlooked this because it is not shown in the log file. It has already been fixed and will be pushed in the next few days.

**Comment by bluewaysw** [comment]
This should have been fixed in the latest master CI release, please confirm and close. @nschulux

**Comment by nschulux** [comment]
Fixed in last  Build.
