### ISSUE TITLE
Apps from Desk Accessoires won´t stay in Foreground ( german Build only )

### ISSUE THREAD

**Issue by lockesoft66** [bluewaysw/pcgeos#363]
I start PC/GEOS (German Build with Releasdates from 26.11.23 till  01.01.2024)
Start an Program GeoDraw at example. make it Fullscreen (optional)
start something from DeskAccessoires and click on the App in Background
The app from DeskAccessoires switch to Background.
Only the Time Dsplay from Clock stay in Foreground.
btw. in GeoManager the Directory is called Des Accessoires and in Preferences the Director ist name with Hilfsprogramme ( german )

Ich startete PC/GEOS( DeutscherBuild mit Releasedaten vom 26.11.2023 bis zum 01.01.2024)
Starte ein Programm GeoDraw zum Beispiel mache es in VollBild (Optional)
Und starte etwas aus dem DeskAccessoires-Ordner und klicke dann auf die vorher gestartete App im Hintergrund
Die App aus DeskAccessoires verschwindet direkt in den Hintergrund.
Alle die Zeitanzeige der Uhr bleibt im Vordergrund.
so nebenbei erwähnt:  Im GeoManager heisst das Verzeichnis Desc Accessoires währens es in den Voreinstellungen als Hilfsprogramme benannt wird.
Möglich, das da schon irgendwas eingedeutsch wurde, was noch nicht überall angekommen ist.

**Comment by nschulux** [comment]
We should rename the Folder to "Hilfsprogramme" and also Games to "Spiele".
Then the Geode stays in top.

**Comment by rabe-soft** [comment]
I'm working on it.

**Comment by lockesoft66** [comment]
I guess right, resolution is in filetree

**Comment by nschulux** [comment]
> I guess, resolution is something like "clone" world-directory with different subdirs for the languages in bbxensem.filetree? Like the Solution for Helpfiles.

Clone was a solution but all the translation files must be adapted! 
So try this way but someone must test this under real Dos to see if this works.

**Comment by bluewaysw** [comment]
There is an solution we agreed on implemented and merged to master, german version now comes with german folder name. Please double check.

**Comment by nschulux** [comment]
It works in Dosbox 2017 and also on real DOS.
![DosBox2017](https://github.com/bluewaysw/pcgeos/assets/118665816/52529455-e5e3-42fc-9736-3d0370d24090)

**Comment by lockesoft66** [comment]
cleared with Release from 05.01.2024

**Comment by lockesoft66** [comment]
in my dosbox-installations it works too. 
I close this Issue
