### ISSUE TITLE
Character Map crashed when "Copy to Clipboard" is pressed

### ISSUE THREAD

**Issue by bluewaysw** [bluewaysw/pcgeos#374]
![grafik](https://github.com/bluewaysw/pcgeos/assets/45116648/cb7be60e-fde9-4f64-bf0c-e7bb20f6588d)

(when running in ec swat?)

**Comment by rabe-soft** [comment]
Ups. I know this error, I think, this is associaded with the order or the value of the parameters, passed to a "select text" message. 
I will put this on my todo list and fix it.

**Comment by rabe-soft** [comment]
fix done
