### ISSUE TITLE
Motif should support the Taskbar as well.

### ISSUE THREAD

**Issue by HubertHuckevoll** [bluewaysw/pcgeos#407]
There should be an option in Motif to use the Taskbar along with ISDesk and the "regular" Express-Menu.

**Comment by dnesbitt142** [comment]
This probably should be a separate issue, but here it goes, I'd also suggest that the task bar should be moveable (as it could be positioned at the top of the screen like in NDO 3.2a), and perhaps also hidden like when GeoPoint is in presentation mode?

**Comment by HubertHuckevoll** [comment]
The patch I linked above also provides the capability to set the Taskbar movable again.

**Comment by dnesbitt142** [comment]
Brilliant, thank you!
