### ISSUE TITLE
World-directory is named with upper and lowercase Letters

### ISSUE THREAD

**Issue by lockesoft66** [bluewaysw/pcgeos#432]
it should be named with Capitals only because: If you use ini-Paramter "path" to "mount" external directorys into /World the additionall Directory was named /WORLD. Two World directorys are shown.

Das World -Verzeichnis ist mit gemischte Groß- und Kleinschreibung bezeichnet. Es sollte nur mit Großbuchstaben bezeichnet werden. Wmm man den Ini-Paramter Path nutzt um ecterne Verzeichnisse in World einzublenden, werden diese in /WORLD eingeblendet. Im Ergebnis werden Zwei world-Verzeichnisse angezeigt.

**Comment by bluewaysw** [comment]
The DOS file name is "world", lower case in the packaging but similar to document and the other folder. "World" is the long file name given by @dirname.000.

**Comment by bluewaysw** [comment]
It is effect of DIR(World) is being used in bbxensem.filetree. Changing to DIR(world) should fix the issue, at lease the inconsitency and related miss-behaviour.

**Comment by lockesoft66** [comment]
I hope i understand you right. I take a look at the bbxensem.filetree.
Change this one letter ( maybe it is often repeated an more places, but...) and this will fix this Issue.
Ok. Stay tuned for my PR.
Regards Klaus / Locke

**Comment by lockesoft66** [comment]
done with Pull Request 451
