### ISSUE TITLE
SysTrayClock appears in Expressmenu in Sektion running Programs. In Motif too

### ISSUE THREAD

**Issue by lockesoft66** [bluewaysw/pcgeos#448]
SysTrayClock is only useful at ISUI, is startet at every Systemstart. Now in Motif the SysTrayClock is shown as a "running Program" in Expressmenu

**Comment by HubertHuckevoll** [comment]
This should be fixed when #515 gets merged...

**Comment by lockesoft66** [comment]
Is fixed. I close the Issue.
Thx
best Regards Klaus / Locke
