### ISSUE TITLE
Click sound

### ISSUE THREAD

**Issue by hanslse** [bluewaysw/pcgeos#477]
Click sounds in floating keyboard is always on and not possible to turn off in Preferences. The click sound could also be improved, replaced with a real discreet click sound, now it is more of a loud chime.

**Comment by hanslse** [comment]
I have noticed that there is a click sound in the PC speaker driver. First I thought it was the PC speaker driver that could not produce the same sound as in the SoundBlastee driver, but when listening to the sound in headphones, it is a different sound and way shorter in time.

**Comment by bluewaysw** [comment]
The sound has been improved, change has been merged to master. The improvement has been approved, so lets close this ticket.
