### ISSUE TITLE
KR-09 crash in Motif Redux

### ISSUE THREAD

**Issue by hanslse** [bluewaysw/pcgeos#495]
KR-09 crash in Motif Redux when adding "lr resize border thickness" and "tb resize border thickness" to the [motif options] in geos.ini and setting the value to something different than the default value 5. If you set the value to 3 or 4 Geos will crash with a KR-09. Setting it to 5 or not adding anything, no crash.

**Comment by HubertHuckevoll** [comment]
Thanks for reporting! Does this work in regular Motif and ISUI?

**Comment by hanslse** [comment]
ISUI is not affected of this setting in Geos.ini. It works without KR-09 crash in MotifUI. It crashes in Motif Redux .Sorry, for the delayed answer.
