### ISSUE TITLE
Maze Screensaver Module translation

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#510]
Only Maze Options not translable Resedit says no Resource to translate. 

Maze war mit Labyrinth übersetzt , aber das Module kann nicht geändert werden so habe ich den wieder Maze benannt dann werden die Optionen angezeigt, aber Maze Options. Wieleicht kann man das im Code (Assembler) ändern.

![image](https://github.com/bluewaysw/pcgeos/assets/118665816/54510615-107f-47ed-a033-c1f9137c5602)

**Comment by nschulux** [comment]
Heute habe ich nochmal mit Maze getestet , da gibt es keine Optionen im Dialog.
Hier gibt es nur OK und Zurücksetzen aber ausgegraut und nie verwendbar.

So kann ich Maze in Labyrinth umbenennen dann werden die Maze Options nicht angezeigt.

**Comment by rabe-soft** [comment]
Please don't rename the English program. And be careful with the translation, because there is a "Maze runner" application too.
I assume that only a flag or something similar has to be set in the code to avoid the Maze Options button.

**Comment by nschulux** [comment]
I have Renamed Maze to the PR.
