### ISSUE TITLE
Password-dialog in Preferences KidGuard aka Netzwerksperre or parental Control is not translatable

### ISSUE THREAD

**Issue by lockesoft66** [bluewaysw/pcgeos#528]
In Netzwerksperre ist der Dialog zum Einschalten der Sperre, der ja eine Angabe eines Passworts verlangt nicht übersetzbar. Die Texte tauchen in der Übersetzungsdatei nicht auf

**Comment by nschulux** [comment]
Library parentc.geo in Systemordner enthält Passwort Dialoge.
Werde Übersetzungsdatei hinzufügen zum Github.

**Comment by lockesoft66** [comment]
Ich habe nachdem Rainer mir den Hinweis auf die richtige Datei gegeben hat eine Übersetzer-Datei hier selber erstellt und auch bereits übersetzt, wartete nur auf eine Ansage zum Namen (Dos) damit der automatische Übersetzer die Datei auch findet. Sonst wäre die Datei gestern schon in einem PR verarbeitet worden. Das war mal wieder doppelte Arbeit. :-(

**Comment by nschulux** [comment]
Ich habe die von Johannes upgedated , er hatte mir seine Übersetzungen geschickt.
Sorry war ich wieder zu schnell.

**Comment by lockesoft66** [comment]
Gibt schlimmeres. 🙂
Wir warten jetzt den PR ab. 
Danach bastel ich aus den vorhandenen Übersetzungen eine einzige Übersetzung. Weil, 
Im Moment finde ich schon, dass man sehr deutlich merkt, dass die Drei zusammen gehörenden Teile irgendwie zu verschiedenen Zeiten von verschiedenen Leuten gemacht wurden.  Verschiedene Begriffe für die gleichen Dinge und sowas.
Grüße Klaus

**Comment by nschulux** [comment]
PR geschlossen da Klaus shon an der Library parentc.geo Übersetzung arbeitete. Es ist besser wenn nur eine Person an einem Problem arbeitet.  Selbe Begriffe und Beschreibungen -> Hilfe <-> Übersetzung da gebe ich Klaus recht.

**Comment by lockesoft66** [comment]
I close this Issue, cause a New Translationfile was created. Now i can translate this item. 
Das Issue schließe ich hiermit dann auch mal. Eine neue Übersetzungsdatei wurde creiert. Jetzt ist diese Stelle übersetzbar.
