### ISSUE TITLE
Absolute paths in make file of makedpnd

### ISSUE THREAD

**Issue by bolle732** [bluewaysw/pcgeos#54]
The file `pcgeos/Tools/pmake/makedpnd/Makefile` has still absolute paths from Falk. This prevents others from building the tool chain.

**Comment by bolle732** [comment]
Maybe something like this:
```
diff --git a/Tools/pmake/makedpnd/Makefile b/Tools/pmake/makedpnd/Makefile
index 60fda44..73ca311 100644
--- a/Tools/pmake/makedpnd/Makefile
+++ b/Tools/pmake/makedpnd/Makefile
@@ -1,16 +1,16 @@
 obj_files = fileargs.obj makedpnd.obj
 
 .c.obj
-       wcc386 -d_LINUX -i=/home/frehwagen/watcom-v2/lh -i=/home/frehwagen/watcom-v2/h -i=../../include -i=../src/lib/include -i../src/lib/lst -i=c:\g6_\pcgeos\include -i=../customs -fo=$*.obj $<
+       wcc386 -d_LINUX -i=$(%WATCOM)/lh -i=$(%WATCOM)/h -i=../../include -i=../src/lib/include -i../src/lib/lst -i=../customs -fo=$*.obj $<^M
 
 makedpnd.exe: $(obj_files)
   %write pmake.lnk NAME   $@
   %write pmake.lnk FORMAT ELF
   %write pmake.lnk libfile ../lib/sprite/sprite.lib
   %write pmake.lnk libfile ../lib/lst/lst.lib
-       %write pmake.lnk library /home/frehwagen/watcom-v2/lib386/linux/clib3r.lib
-       %write pmake.lnk library /home/frehwagen/watcom-v2/lib386/linux/emu387.lib
-       %write pmake.lnk library /home/frehwagen/watcom-v2/lib386/math387r.lib
+       %write pmake.lnk library $(%WATCOM)/lib386/linux/clib3r.lib^M
+       %write pmake.lnk library $(%WATCOM)/lib386/linux/emu387.lib^M
+       %write pmake.lnk library $(%WATCOM)/lib386/math387r.lib^M
   %write pmake.lnk FILE   {$(obj_files)}
 
   wlink  @pmake.lnk
```

**Comment by bluewaysw** [comment]
Hi, take care, all Tools beside pmake itself and depending libraries, are build from Installed folder using pmake. So all makefiles that are not living in Installed (and are not pmake itself) should be removed from the repo.

**Comment by bluewaysw** [comment]
Maybe the comment here help to get the tools built in the current state:
https://github.com/bluewaysw/pcgeos/issues/27
I removed the Makefile mentioned above.

**Comment by bolle732** [comment]
Thanks for the reminder. Yes, I followed the instruction to build pmake with wmake and then the whole toolchain with pmake. And there I got the error 139, segmentation fault. As far as I could debug, I ended there editing the make file.

Lets see, if I can build everything from a clean checkout.

**Comment by bluewaysw** [comment]
Ok, understand. I think there is some timing related issues with the Linux version of pmake, maybe related to file system speed or CPU. But the better solution then is to investigate this problem and fix it, because this will be required anyhow.

**Comment by bolle732** [comment]
On my other notebook, I got the error in/after esp:
```
--- Tools/esp:installlinux ---
for i in linux.md/esp linux.md/printobj linux.md/printsls ;  do cp $(echo "$i." | sed 's/.exe.$/.exe/') /home/andreas/Development/pcgeos/bin/$(basename "$i") ; done
Segmentation fault (core dumped)
*** Error code 139
pmake: 1 error
```
I did the follwing:
```
wget https://github.com/open-watcom/travis-ci-ow-builds/archive/master.zip
unzip master.zip
mv travis-ci-ow-builds-master watcom
git clone https://github.com/bluewaysw/pcgeos.git
cd $ROOT_DIR/Tools/pmake/pmake
wmake install
cd $ROOT_DIR/Installed/Tools
pmake install
```
My `.bashrc` contains:
```
# PC/GEOS SDK
export WATCOM=$HOME/Development/watcom
export EDPATH=$WATCOM/eddat
export INCLUDE=$WATCOM/lh:$WATCOM/h
export ROOT_DIR=$HOME/Development/pcgeos
export PATH=$ROOT_DIR/bin:$WATCOM/binl64:$WATCOM/binl:$PATH
```
```

**Comment by jirkakunze** [comment]
Can you reproduce the problem if you call pmake in .../Installed/Tools/esp? This only builds esp.

**Comment by bolle732** [comment]
Yes, I've did that too and I think it helped on my second notebook with termination during 'esp'. I also did a make inside the next target `uicpp`.

The first problem was with `makedpnd`. There I tried to build parts from a lot of different locations. Even in the wrong directories...

One thing I observed is, that both Linux and Windows binaries are built. In case of an error, I had sometimes only the Linux binary and the Windows one was missing in ` $ROOT_DIR/bin`.

If it could be a timing problem, is there an option to force `pmake` only to use one thread / CPU ? Or is that by default ?

**Comment by jirkakunze** [comment]
Since the corrections to the Makefiles I had no problems building Windows or Linux binaries under Linux.

I will try to investigate the problem on a newly created sandbox.

**Comment by bolle732** [comment]
Maybe it's a concurrency problem. Both notebook have an i7 CPU with SSD.

What's the reason to build both Linux and Windows binaries under Linux?

**Comment by bolle732** [comment]
On a vanilla checkout, removing the build of Windows binaries solves the problem. All Linux binaries are built without an error.

So, it really looks to be a concurrency problem.

```
$ git diff
diff --git a/Installed/Tools/Makefile b/Installed/Tools/Makefile
index 6a325d97..7cd833d9 100644
--- a/Installed/Tools/Makefile
+++ b/Installed/Tools/Makefile
@@ -31,8 +31,7 @@ $(BINS) : $(LIBS)
 #if defined(linux)
        mkdir -p $(ROOT_DIR)/Installed/$(.TARGET) ; \
        cd $(ROOT_DIR)/Installed/$(.TARGET) ; \
-       $(MAKE) -k -I$(ROOT_DIR)/Installed/$(.TARGET) installlinux ; \
-       $(MAKE) -k -I$(ROOT_DIR)/Installed/$(.TARGET) installwin32
+       $(MAKE) -k -I$(ROOT_DIR)/Installed/$(.TARGET) installlinux
 #else
        mkdir $(ROOT_DIR)\Installed\$(.TARGET:S/\//\\/g) & \
        cd $(ROOT_DIR)\Installed\$(.TARGET:S/\//\\/g) & \
```

**Comment by jirkakunze** [comment]
Oops, I did a PR on this Makefile a few days ago.

**Comment by jirkakunze** [comment]
Is there still a semicolon needed after installwin32?

**Comment by bolle732** [comment]
Looking at the `make.c` of `pmake`, it looks that it really does multiple jobs in parallel (ok, on MS-DOS one by one...)

**Comment by bluewaysw** [comment]
Yes, the linux version does parallel building, not perfectly as it seems, there are also connection points to build on muliple machines.
