### ISSUE TITLE
Outliner crash if choose printpreview.

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#597]
Outliner crash if we select menu printpreview !
![OLDruckFreeGeos](https://github.com/bluewaysw/pcgeos/assets/118665816/fef7b1c6-cfa0-4930-a080-4547eed46009)

Under BBX it works !
![OLDruckBBX](https://github.com/bluewaysw/pcgeos/assets/118665816/eaf126c9-97ad-406a-9a36-167ec8ab148c)

**Comment by nschulux** [comment]
Achim meldete das nun auch in GeosInfobase.

**Comment by rabe-soft** [comment]
Bug found. About to fix it.
