### ISSUE TITLE
TTF driver: printing in PS file incorrect with some fonts

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#603]
I have replaced Nimbus Sans with Hinting Info but now it's printed faulty in PS file.
Perhaps Kerning faulty ?
Original Font make same fault.

Font in previous Version was printed correcty in PS file.

New Font with Hinting:
![image](https://github.com/user-attachments/assets/4cbbf4eb-292b-493f-b8f5-c1b117659d06)

Old Font :
![image](https://github.com/user-attachments/assets/70377cf9-49a5-4d8e-a970-f37517d1b6e5)

**Comment by jirkakunze** [comment]
The font Nimbus Sans Regular in the repository has no kerning table. I assume you have added kerning information to your version of the font. Can you post your version of the font here to analyze it?

**Comment by nschulux** [comment]
Old Font that Works.
[nimbsre.zip](https://github.com/user-attachments/files/16240421/nimbsre.zip)

How can i see if Kerning is in the Font ?

**Comment by jirkakunze** [comment]
Not all fonts are affected:
![grafik](https://github.com/user-attachments/assets/51927bb6-8a5d-44cc-b759-d50d5429aca7)

affected:
- Nimbus Sans (has no kerning table)
- NYT Franklin (has no kerning table)
- Century 59 (has no kerning table)
- Cooper* Black (has no kerning table)
- Futura  (has kerning)

@nschulux With which version of the TTF driver (creation date) did you successfully test the scenario?

**Comment by nschulux** [comment]
I am not sure when we testet , but I am not sure if we tested the Printing.


I have sayed to Falk that some Fonts have Fault prints.


The Nimbus Sans that is OK has no Hintings.



I Attache you the Font.


I can't see the Kerning  Info.


If I print toPS with Postscipt kompatibel that Works so:




Fonts are from here:


ArtifexSoftware/urw-base35-fonts: Repo for URW++ base 35 font set (github.com)


from Nico


Am 16.07.2024 um 10:58 schrieb Jirka Kunze ***@***.***>:



Not all fonts are affected:
grafik.png (view on web)

affected:
 Nimbus Sans (has no kerning table)
NYT Franklin (has no kerning table)
Century 59 (has no kerning table)
Cooper* Black (has no kerning table)
Futura (has kerning)

@nschulux With which version of the TTF driver (creation date) did you
successfully test the scenario?

**Comment by nschulux** [comment]
Could it be the Hinting information that makes this Error ?

I can't add kerning I can not work with fonts.


from Nico


Am 15.07.2024 um 22:55 schrieb Jirka Kunze ***@***.***>:



The font Nimbus Sans Regular in the repository has no kerning table. I assume
you have added kerning information to your version of the font. Can you post
your version of the font here to analyze it?

**Comment by nschulux** [comment]
I have now found a way to solve the Issue , with FontForge I open the ttf and has created a Codepage Geos.
Create the Font from source and print now with GhostScript to PS correctly.
![image](https://github.com/user-attachments/assets/51584a0b-981e-41ab-92a6-9990839c1ea3)

**Comment by nschulux** [comment]
Now i have seen Fonts print not always in Bold :
![image](https://github.com/user-attachments/assets/1ae41610-742c-41eb-ac64-8e8af85cafdb)
![image](https://github.com/user-attachments/assets/b6c08bbd-a369-46d3-bb55-d0e6672ab7d2)
In Geowrite tey are displayed correctly !
Fonts also in Windows shown correctly !
Checked all Font Subfamilies are OK.

**Comment by jirkakunze** [comment]
As I only have a little information, I can only speculate.
The print with Nimbus Sans looks as if the style bold and bold/italic were calculated by the driver. This may be because these styles were not found. If I remember correctly, you have renamed the Nimbus Sans L font to Nimbus Sans. This could be the problem, because the font family name is used to create the font ID. If the styles have a different family name (a typing error is enough), then a different font ID is also calculated and for GEOS this is then a different font.

I do not understand the sense or purpose of this renaming. Why is it a problem if the font is called Nimbus Sans L?

**Comment by nschulux** [comment]
In PC/GEOS  Geowrite the Font is shown correctly the rename was better to replace URW Sans and Displays correct in the Font Tool.
It was also Falk who found this better.
![image](https://github.com/user-attachments/assets/6cdcfc9a-36e7-415a-8e77-7df246ceb318)

**Comment by nschulux** [comment]
I have tried the Nimbus SanL without modifiecations : 
![image](https://github.com/user-attachments/assets/8863323d-ccea-4561-b8ef-bfc917ac5844)

**Comment by nschulux** [comment]
Here the two PS files NMONO4.PS and NSANS4.PS look inside with TextEditor at my advice the PS Driver doesen't handle the Bold not correctly.
[spoolPS.zip](https://github.com/user-attachments/files/16432182/spoolPS.zip)

**Comment by jirkakunze** [comment]
Problem found why the horizontal position is not correct when printing PS. I hope I can submit a PR for this at the weekend.

**Comment by nschulux** [comment]
Great Work !!!
With wich Font You tested ? With them in the Build ?
Should I close the PR with Updated Fonts !
What is with the BOLD in PS Printing ?

**Comment by jirkakunze** [comment]
I have tested the fix with different fonts (Futura, original Nimbus Sans L, Cooper*Black, PT Mono, PT Sans). 
Unfortunately, the incorrect printing of the bold style has not been corrected. I have not yet investigated where this problem is.
After correcting the horizontal position when printing, I will continue to work on the problem in the bytecode interpreter.
If the bytecode interpreter runs in the driver, the driver is functionally complete and I can continue with bug fixes and optimizations.

**Comment by nschulux** [comment]
Please test the Font Nimbus Sans from ArtifexSoftware/urw-base35-fonts: Repo for URW++ base 35 font set this I found look better in Bold.
