### ISSUE TITLE
Watcom reports errors in wrong line - this also caused swat to highligt the wrong line

### ISSUE THREAD

**Issue by rabe-soft** [bluewaysw/pcgeos#611]
Under certain circumstances unknown to me (but not always), watcom reports an error (line 277) in the wrong line (the one above, line 276). 
![grafik](https://github.com/user-attachments/assets/04c0e90d-ad23-4c4d-9f60-1552338c8710)
![grafik](https://github.com/user-attachments/assets/574781c0-27e9-464d-a120-74fc8604db73)

After correcting the error, swat also highlights the wrong line at this point. The highlighted line has already been executed. This is very confusing.
![grafik](https://github.com/user-attachments/assets/826dc5c5-a631-47a3-bba1-f5e46d34bc56)

The reason for this behavior is completely unclear to me. In the specific example, you can remove two comment lines above it and the error will be displayed in the correct line (line 275). 
![Code ok 275](https://github.com/user-attachments/assets/455ebcbf-f0da-4833-9012-5517d869633a)
![grafik](https://github.com/user-attachments/assets/aa35bbb8-509b-4884-902c-6f23d550302b)

Swat then also highlights the correct line ( the one to be executed). It is also not clear why the varwin command no longer works here.
![grafik](https://github.com/user-attachments/assets/1a5412c1-cf5a-497a-ae5d-bf079113ac13)

IMHO this bug should be fixed as soon as possible. It sound very important to me that the compiler and swat works correctly.

**Comment by bluewaysw** [comment]
Likely GOC reports wrong lines or does this happen to pure C files as well?

**Comment by rabe-soft** [comment]
I don't know.

**Comment by mgroeber9110** [comment]
I have definitely seen this as well - the mapping between debug info and source lines appears to be off sometimes.

Could this be related to the `#line` statements in the preprocessed `.ec` files that are produced by _goc_? If I look into one of these files, it has comments removed and occasionally contains lines like `#line 360` to resync the original source line numbering with the lines in the file that the compiler sees. I wonder if there is something that goes wrong in a Watcom-specific way (though I don't have an obvious idea why...).

It may be interesting to regenerate the `.ec` file for a problematic case (as it gets deleted during the build after _wcc_ has run), and look in detail at how the line numbers are calculated.

What would be more annoying is of course a bug deep inside the debug info generation of OpenWatcom... so the question whether this ever happens in plain C files is quite an interesting one. :-)

**Comment by HubertHuckevoll** [comment]
@mgroeber9110 Thank god you find this bug interesting, Marcus :-)

**Comment by rabe-soft** [comment]
Yes the line statements differ in the ec file
When wrong line ist reported
```


#line 267

void BuildWordList(FileHandle srcFile, VMFileHandle listFile) {
#define INWORD_BUFFER_SIZE	(WM_MAX_SIZE_WORD + 40)
#define INWORD_MAX_LEN		(INWORD_BUFFER_SIZE - 2)
int	i, size;
Boolean	stop = FALSE;
dword	read, added;
byte 	c;
char    inWord[INWORD_BUFFER_SIZE];	
char 	number[15];
x;
	
#line 286
```
When correct line is reported (comment removed) there is no leading line statement 

```

void BuildWordList(FileHandle srcFile, VMFileHandle listFile) {
#define INWORD_BUFFER_SIZE	(WM_MAX_SIZE_WORD + 40)
#define INWORD_MAX_LEN		(INWORD_BUFFER_SIZE - 2)
int	i, size;
Boolean	stop = FALSE;
dword	read, added;
byte 	c;
char    inWord[INWORD_BUFFER_SIZE];	
char 	number[15];
x;
	
#line 284

```
@mgroeber9110 If you have a look to the goc/watcom code, please have a look at Issue #421 . Maybe this is related to the current problem. In the next few days I will analyze in more detail when this problem occurs

**Comment by rabe-soft** [comment]
> What would be more annoying is of course a bug deep inside the debug info generation of OpenWatcom... so the question whether this ever happens in plain C files is quite an interesting one. :-)

After replacing the goc fiele by the .ec file (as wlistegn.c) the error is reported in the correct line. This is of course no evidence, because there are also goc files where the error does not occur.

**Comment by rabe-soft** [comment]
The issue was probably added to the repo between December 31, 2023 and January 5, 2024.
If you clone the repo again and enter "git reset --hard 458788' (Dec 31, 2023), copy wmlib and WListeGen over, build all tools and target components, as well as wmlib and WListGen, the error is displayed in the correct line (277). If you repeat the process and enter a "git reset --hard a08d58" (Jan. 5, 2024), the error is displayed in the wrong line (276).
I hope this helps to locate and eliminate the error.

**Comment by mgroeber9110** [comment]
Thanks @rabe-soft. That helps narrow it down considerably. The culprit seems to be PR #365 which merges some of my tool changes to master, but I am not yet sure what inside this fairly harmless-looking changeset is causing it (or even how... it seems that some `#line` statements in the .ec file get added), but the only thing that might even remotely have an effect is the fix to ´i_vfprintf´.

**Comment by mgroeber9110** [comment]
I think I found the reason: line endings! The change I made to `i_vfprintf()` disabled a somewhat unusual conversion of \r to \r\n in `sprintf()`, which meant that `#line` was terminated with \n only, and for some reason that face confused line counting in Watcom. As far as I can see, this conversion only worked previous because of luck in accessing an undefined memory location, and sometimes led to a crash when compiling the browser.

Even with the fix, the .ec files will still be a weird mix of \n and \r\n endings (because include files and the lines that are leftovers from removed comments are transformed from \r\n to \n), but this seems to be okay elsewhere.

I will test this some more and then make a PR.

**Comment by rabe-soft** [comment]
If I can help testing, let me know!

**Comment by mgroeber9110** [comment]
Thanks, @rabe-soft - if you (or anyone else) want to give a try, I have created a Draft PR #612 where you can see the changes.

It would probably be useful to check more widely whether this has any unwanted side effects, besides confirming that it fixes the original issue, as it essentially touches the runtime library shared by all build tools.

**Comment by rabe-soft** [comment]
@mgroeber9110  After manually changing the lines of code (I didn't know how to download the complete file :~( ) the error is shown in the correct line when I use the original dependencies.mk.  But 'pmake depend' seems to generate invalid dependencies.mk, so pmake fails after an mkmf / pmake depend respectively.
![grafik](https://github.com/user-attachments/assets/8faa847b-11fd-4085-819f-7ee5b8fd5c3c)
![grafik](https://github.com/user-attachments/assets/11e11bb9-31ff-497a-9fd6-bda4ea8f2f51)

**Comment by mgroeber9110** [comment]
@rabe-soft: Thanks again. I have pushed another fix with a different set of assumptions of how the printf-style routines should treat CRLF translation (sprintf should *not* translate, but the LF should still go through the translation when printing to file). Also, our code for Watcom was using the wrong flag in the FILE structure to check for a binary file. For me, this now makes both line numbering and `mkmf` work.

To download entire files from the PR, you can click on the "..." next to a file in the PR, then select "View File", and then you get a "Download raw file" icon.

**Comment by rabe-soft** [comment]
Thanks for the explanation. 
The first tests were successful. I'll test a little more and report back tomorrow.

**Comment by HubertHuckevoll** [comment]
Will this patch also fix the same problem for the Linux-based SDK?

rabe-soft ***@***.***> schrieb am Di., 23. Juli 2024, 20:53:

**Comment by rabe-soft** [comment]
@HubertHuckevoll Simply try it. Generate an error which is reported in the wrong line (I simply use the statemenet `paul;` ). Then replace the both files an re-build all tools (including pmake) as described in the readme.md. After that, see if the error is reported in the right code line.

**Comment by rabe-soft** [comment]
@mgroeber9110 Anything seems to be fine. I have tried various apps and two libraries. Errors are reported in the correct line, mkmf works, the rsc files are OK and the translation also works. The correct line is also displayed under swat. Great work!
Any ideas what else can be tested?

**Comment by HubertHuckevoll** [comment]
In Linux we have the same problem of Swat reporting errors in the wrong
line (one off).

mgroeber9110 ***@***.***> schrieb am Mi., 24. Juli 2024,
13:09:
