### ISSUE TITLE
Draft PC/GEOS Ensemble 6.0 startup/default look&feel

### ISSUE THREAD

**Issue by bluewaysw** [bluewaysw/pcgeos#638]
Current proposal:
- use Motif Redux specific UI with ISDesk
- original default Motif colors as basic
- light blue highlight color
- light yellow help background
- default background image: meadows
- smaller 10 pt font
- fast close window button
- world app list direct section in expresss menu
- default background color for the desktop is dark grey

**Comment by HubertHuckevoll** [comment]
What about the splash screen?

**Comment by bluewaysw** [comment]
> What about the splash screen?

Lets deal with this as an different issue....

**Comment by bluewaysw** [comment]
Look&Feel implemeneted and rolled out to master, the CI release.
