### ISSUE TITLE
ttf-driver: poor screen output quality with document zoom

### ISSUE THREAD

**Issue by jirkakunze** [bluewaysw/pcgeos#643]
![grafik](https://github.com/user-attachments/assets/f7bd8148-639f-43f6-8eaf-ce02dfd5e6f7)

**Comment by jirkakunze** [comment]
The solution to the problem is to realize the document zoom not by manipulating the outline of a glyph but via the display resolution. The image above shows the new algorithm and the current algorithm below (Nimbus Roman and Nimbus Sans at 150% document zoom).
![grafik](https://github.com/user-attachments/assets/773955cf-5a9b-4a0a-9a21-5a91e8c85668)

**Comment by bluewaysw** [comment]
Does this mean: Let GEOS scale at output time instead of the the font engine render a different resolution?

**Comment by jirkakunze** [comment]
This means that the outline of a glyph remains untouched (except for rotations, fake styles and given width and weight). Before rendering, the FreeType Rasterizer is now set to a different resolution (i.e. set from 72dpi to 90dpi at 125% document zoom). Then the bitmaps are rendered correspondingly larger and the byte code interpreter is no longer confused because the control values in the cvt table no longer match the values in the outline.
