### ISSUE TITLE
Voreinstellungen -> KR-07

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#662]
Im Letzten Build bleibt bei mir Geos in den Voreinstellungen Schriften hängen.

![image](https://github.com/user-attachments/assets/cd48ecdc-d926-42e9-a61b-3bd06bb0483a)

In älterem Build 14.09 war das noch in Ordnung.

**Comment by nschulux** [comment]
Von Achim: Mit der neuesten CI-Latest-Ausgabe von PC/GEOS 6 Deutsch (ca. 19 Stunden alt) habe ich riesige Probleme. Wann immer ich etwas über die Voreinstellungen ändern möchte, gibt es irgendeinen KR-xx-Fehler. Ich muß das DOSEmu-Fenster dann manuell schließen, es geht nix mehr. Kann das jemand bestätigen?
Von Thomas: ich kann das bestätigen. Das gilt auch für die englische CI Version.
Dosbox 0.74-3/PiGeos mit jeweils cleanen Download

**Comment by HubertHuckevoll** [comment]
Falk has found the problem and will issue a patch very soon.

**Comment by nschulux** [comment]
Good !
