### ISSUE TITLE
Fake block covering 196640 bytes

### ISSUE THREAD

**Issue by rabe-soft** [bluewaysw/pcgeos#668]
Fixing this should solve a lot of out-of-memory problems. Use the heapwalk command under swat:
![grafik](https://github.com/user-attachments/assets/44c9fb16-1c1b-4086-bb96-e95ddec845fb)
![grafik](https://github.com/user-attachments/assets/e96ab879-a656-45d6-b21d-54dfe0a70497)

**Comment by HubertHuckevoll** [comment]
Never seen this before! How to reproduce?

**Comment by rabe-soft** [comment]
Simply run the target, stop to swat promt (Ctrl-c) and enter the command hwalk.

**Comment by mgroeber9110** [comment]
I think this block covers video memory at 0xA000 and space reserved for ROMs on extension cards, if I remember correctly (see https://web.archive.org/web/20100330185414/http://www.frontiernet.net/%7Efys/rombios.htm). So, it is probably not available for mapping additional RAM into the address space.

**Comment by rabe-soft** [comment]
Ok, thanks.
