### ISSUE TITLE
FreeGEOS system performance degrades when using network enabled programs (i.e. Webmagick and IRC client) when running on FreeDOS 1.3

### ISSUE THREAD

**Issue by dnesbitt142** [bluewaysw/pcgeos#678]
Hello,

I thought I should add this as a formal issue, during and after using programs that use the network/internet (i.e. WebMagick, IRC chat) using the packet ethernet driver, there is a very noticeable degradation in FreeGEOS performance during and after closing such applications. I have come across this when running FreeGEOS on FreeDOS 1.3 on a P3 era Celeron. Based on the discussion on Discord, the problem may lie with the Packet Ethernet Driver, or the Socket components of the system. This issue affects the master branch and the issue-149 branch too. [Video of the issue here](https://www.youtube.com/watch?v=yB-zG_PiMSE)

Cheers,

Dan

**Comment by bluewaysw** [comment]
The driver in FreeGEOS uses a independent high prio thread to process incoming data. This is by mistake not synced with actual incoming data and is also not destroyed on shutdown. This has been introduces over 10 year ago when making the driver work for DosEMU (as used in the GeoLive CD) and for the QuickPAD project. It seems it has been left unfinished somehow.

The separation into an thread was requited to make the driver work reliable. This likely realed to the DOS driver used and there are no details know on the environment.

Fresh tests now on 86box without the thread beeing used show stable operation, so we go into testing the version of etherpkt without using a separat thread. If there is the need in one or the other environment to have the thread we will reintegration a solution. For now let test and make the pure version stable.

**Comment by bluewaysw** [comment]
The fix has been implemented and merged to master. @dnesbitt142 did you had a chance to retest the issue, it is solved from your point of view?

**Comment by dnesbitt142** [comment]
> The fix has been implemented and merged to master. @dnesbitt142 did you had a chance to retest the issue, it is solved from your point of view?

Hi @bluewaysw yes I have tested it since its merge into Master and it seems to be working well on both DOSBox-X and my P3 Celeron Box, thanks for fixing it.

**Comment by bluewaysw** [comment]
OK, thank you, then lets close this issue, raise a new one for further issues that might arise.
