### ISSUE TITLE
The font size in the User Notes section of the file information dialog in the file manager differs from the rest of the dialog

### ISSUE THREAD

**Issue by QRV71** [bluewaysw/pcgeos#755]
If you open the file information for a file in GeoManager (the file manager), there is a field there for user notes.
The font size used in this field is not the same as the rest of the UI in FreeGEOS.
There seems to be a size difference.

I have added a screenshot to clarify what I am referring to.

![FreeGEOS - File Manager - User Notes font size differs from rest of dialog](https://github.com/user-attachments/assets/53300b9b-78d8-421f-a6af-3eaae676e9d8)

Please, make sure font use is consistent throughout the UI.

**Comment by QRV71** [comment]
As Falk pointed out to me in Discord. Apparently, the font size for text had been set to 12 pt instead of 10 pt in the UI Preferences. I just don't know how that happened. Perhaps a check if the default setting is still equal can be done, but other than that, issue resolved.

**Comment by jirkakunze** [comment]
Can you please close this issue when it is done?

**Comment by bluewaysw** [comment]
OK, lets close for now but keep an eye on it when testing. If a related issue is coming up we may create a new ticket for it or reopen this one.
