### ISSUE TITLE
Error KRX-620/375 when running in DOSBox

### ISSUE THREAD

**Issue by m23project** [bluewaysw/pcgeos#86]
Hi,

I got the source compiled with the attached script [make.zip](https://github.com/bluewaysw/pcgeos/files/5026791/make.zip). The script  basically contains the BASH code from ".travis.yml" with slight modifications. Under Debian 10 (amd64) it compiles and produces .geo files, etc. under _out/localpc.

First thing I noticed many files haaving "ec" attached before the extension. Eg. geos.ini becomes geosec.ini, loader.exe becomes loaderec.exe, ...

Then I tried to run loaderec.exe in DOSBox (0.74-2 under Debian 10/amd64) with this configuration [dosbox-conf.zip](https://github.com/bluewaysw/pcgeos/files/5026824/dosbox-conf.zip). The spash is shown, but then an KRX-620 error occurrs.

It seems to have something to do with the file system driver. If I change 

fs = os2ec.geo

into

fs = ms4ec.geo

in geosec.ini the error is KRX-375.

Any ideas what could be wrong?

Cu Hauke

**Comment by jirkakunze** [comment]
I suspect the problem is in the configuration of the DosBox. Can you post your Conf file here?

**Comment by m23project** [comment]
The config is in https://github.com/bluewaysw/pcgeos/files/5026824/dosbox-conf.zip .

**Comment by jirkakunze** [comment]
I have tested her configuration file. PC/Geos will start correctly. If you post your geosec.ini I can also test it.

It should be mentioned that the PC/Geos is still in work. To start it you still need the fonts which are not available here as source code. This is still an open task. Help is always welcome.

**Comment by m23project** [comment]
I had to append ".txt" to make it upload: [geosec.ini.txt](https://github.com/bluewaysw/pcgeos/files/5037725/geosec.ini.txt). This is the last version I tried. 

Basically I changed

fs = os2ec.geo

into

fs = ms4ec.geo

and vice versa.

As from the names in the source tree I would guess that TTF (Driver/Font/Bitstream/TrueType) and Type1 (Driver/Font/Bitstream/Type1) fonts are supported. Is it true? So it would be possible to use a free font? How can I configure it? Setting in geosec.ini?

For help with PC/GEOS development you should get into contact with the FreeDOS project (http://freedos.org/). Jim Hall (the founder) is very interested in PC/GEOS and may help to find supporters.

**Comment by jirkakunze** [comment]
Replace the line fs=ms4ec.geo with primaryfs=os2ec.geo, this fixes the problem. 
But you will get a different message indicating the missing fonts.

**Comment by m23project** [comment]
Unfortunately it doesn't help. It gives me KRX-620 or KRX-375 depending on the value I choose for fs/primaryfs. There is no message about missing fonts. For completeness I copied the font files (userdata/font/*.fnt) from Ensemble 4.13 to userdata/font in the self-compiled PC/GEOS.

Here is the result of compiler, if you like to test: [ensemble-2020-08-08.zip](https://github.com/bluewaysw/pcgeos/files/5049122/ensemble-2020-08-08.zip)

The original Ensemble 4.13 runs with "fs = os2.geo" and the https://github.com/bluewaysw/pcgeos/files/5026824/dosbox-conf.zip .

**Comment by jirkakunze** [comment]
Oh, I made a mistake. primaryfs**d** is the right keyword.

**Comment by m23project** [comment]
That did the trick :-) Thank you :-)
