### ISSUE TITLE
Missing wccrtl functions need reimplementation.

### ISSUE THREAD

**Issue by bluewaysw** [bluewaysw/pcgeos#87]
We discussed to have a 386 based implementation first, this is easier to implement.

**Comment by jirkakunze** [comment]
A short description of the required rtl functions for the Watcom compiler:

Function:  __U4M

Description: 
	Multiplies two unsigned 32bit integers.

	In:   dx:ax	int1 ( dx: high( int1 ); ax low( int1 ) )
		cx:bx	int2 ( cx: high( int2 ); bx low( int2 ) )

	Out: dx:ax	product of int1 and int2

Status:
	Implemented and tested.

=====================

Function:  __I4M

Description:
	Multiplies two signed 32bit integers.

	In:   dx:ax	int1 ( dx: high( int1 ); ax low( int1 ) )
		cx:bx	int2 ( cx: high( int2 ); bx low( int2 ) )

	Out: dx:ax	product of int1 and int2

Status:
	Implemented by delegating to __U4M.

====================

Function:  __U4D

Description:
	Division of unsigned 32bit integers.

	In:   dx:ax	dividend
		cx:bx	divisor

	Out:	 dx:ax	qoutient
		cx:bx	remainder

Comment:
	Probably a simpler implementation is possible by using the 386 instruction DIV r/m32.

Status:
	Not yet implemented.

====================

Function:  __I4D

Description:

	Division of signed 32bit integers.

	In:   dx:ax	dividend
		cx:bx	divisor

	Out:	dx:ax	qoutient
		cx:bx	remainder

Comment:
	Probably a simpler implementation is possible by using the 386 instruction IDIV r/m32.

Status:
	Not yet implemented.

====================

Function:  __CHP

Description:
	Sets the rounding mode and rounds the top element of the FP stack.

Comment:

Status:
	Implemented and tested (not yet merged into the master).

**Comment by bluewaysw** [comment]
This has been merged to master by https://github.com/bluewaysw/pcgeos/pull/84. For now this is considered closed based on the 386 implementation of the runtime function.
